### ISSUE TITLE
Error: bad argument #3 to '?' (number expected, got nil)

### ISSUE THREAD

**Issue by MixMe** [DmitryUlyanov/texture_nets#11]
Command:
th stylization_process.lua -model supplementary/stylization_models/mosaic_style.t7 -input_image data/textures/tiger.jpg -noise_depth 3

/home/ai2/torch/install/bin/luajit: /home/ai2/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.Concat:
In 1 module of nn.Sequential:
In 1 module of nn.Concat:
In 1 module of nn.Sequential:
In 1 module of nn.Concat:
In 1 module of nn.Sequential:
In 1 module of nn.Concat:
In 2 module of nn.Sequential:
bad argument #3 to '?' (number expected, got nil)
stack traceback:
	[C]: at 0x7fd61fcb31a0
	[C]: in function '__newindex'
	./src/utils.lua:148: in function <./src/utils.lua:144>
	[C]: in function 'xpcall'
	/home/ai2/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/ai2/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ai2/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/ai2/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/ai2/torch/install/share/lua/5.1/nn/Concat.lua:12: in function </home/ai2/torch/install/share/lua/5.1/nn/Concat.lua:9>
	[C]: in function 'xpcall'
	...
	[C]: in function 'xpcall'
	/home/ai2/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/ai2/torch/install/share/lua/5.1/nn/Concat.lua:12: in function </home/ai2/torch/install/share/lua/5.1/nn/Concat.lua:9>
	[C]: in function 'xpcall'
	/home/ai2/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/ai2/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	stylization_process.lua:38: in main chunk
	[C]: in function 'dofile'
	.../ai2/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/ai2/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/ai2/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	stylization_process.lua:38: in main chunk
	[C]: in function 'dofile'
	.../ai2/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

**Comment by DmitryUlyanov** [comment]
Make sure your image dimensions are a factor of 32 first. It is the most common problem, maybe it is the reason here too.

**Comment by MixMe** [comment]
I've tried with images from your examples set. Here tiger.jpg has 1024x576. Both W and H are factor of 32. The same issue with kitty.jpg

**Comment by DmitryUlyanov** [comment]
If you are using a pretrained model you need to use the notebook.
