### ISSUE TITLE
Symbol lookup error 

### ISSUE THREAD

**Issue by djebm2** [DmitryUlyanov/texture_nets#14]
Just decided to have a bit of fun with stylized images, but I got the symbol lookup error. I have installed all the needed dependencies through the script several times, but in vain.

Here is what I got:
```
Successfully loaded data/pretrained/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
conv1_1	: padding set to 0	
Setting up texture layer  	2	:	relu1_1	
/usr/bin/luajit: symbol lookup error: /usr/lib/lua/5.1/libTHCUNN.so: undefined symbol: THC_overlappingIndices
```

Thank you for your help.

**Comment by DmitryUlyanov** [comment]
Wow, never seen something like this. There is something with torch installation rather than with repo.  You'd better ask at torch community.

**Comment by djebm2** [comment]
ok thx.

**Comment by austingg** [comment]
@djebm2  make sure your cudnn version is 5.0. By default, the cutorch will be installed using R5 branch which depend on cudnn v5.
