### ISSUE TITLE
Could you please provide a pretrained model for testing?

### ISSUE THREAD

**Issue by puppet101** [DmitryUlyanov/texture_nets#17]
Hi, It's great to see the code updating. But I cannot find a pretrained model in this version. It will be very nice if you can upload a pretrained model by which I can have a test quickly!

Thank you~

**Comment by vnhwd** [comment]
Also I can't find any code about instance normalization, will you update the code about it? Thanks.

**Comment by tkach1024** [comment]
Just use batch_size=1 that's instance norm.

**Comment by DmitryUlyanov** [comment]
I will see If I can upload the model. 

You can use any batch size with this code.

**Comment by DmitryUlyanov** [comment]
added one
