### ISSUE TITLE
error: `module 'src/utils.lua' not found`

### ISSUE THREAD

**Issue by jyhjinghwang** [DmitryUlyanov/texture_nets#2]
I tried 
`th texture_train.lua -texture data/textures/red-peppers256.o.jpg -model_name pyramid -backend nn -num_iterations 1500 -vgg_no_pad -normalize_gradients`
but there's an error message: `module 'src/utils.lua' not found:No LuaRocks module found for src/utils.lua`

I also used th in the root directory of texture_net, and typed `require 'src/utils.lua'`, the error message was the same.

I'm very new to Torch, and I almost installed all the packages. It seems like a path setting issue, but I have no idea how to fix it. Could anyone give me some hint? 
Thanks!

**Comment by DmitryUlyanov** [comment]
Can you please type `require 'src/utils'` in `th` being in root directory? Does it work for you?

**Comment by jyhjinghwang** [comment]
Yes, that was what I did for debugging. But it didn't work.

**Comment by DmitryUlyanov** [comment]
You tried `require 'src/utils.lua'`, please try `require 'src/utils'` (no `.lua` part).

**Comment by jyhjinghwang** [comment]
It worked! Now the problem is CuDNN version. I'll solve it. Thanks a lot for the help!

**Comment by DmitryUlyanov** [comment]
Fixed it.
