### ISSUE TITLE
Typos in your paper?

### ISSUE THREAD

**Issue by eriche2016** [DmitryUlyanov/texture_nets#23]
Hi, I noticed a place( in part `Network architecure` in `Section 3.2 Generator network for texture synthesis` ) in your paper on texture nets where you mentioned that you use different scale of noise tensors which are `1/2M, 1/4M, .... `of the image size repectively. However, in your code on texture nets, you do use `noise tensor` of size `M x M`, which is the same as the input image size. Does this means that in your paper, variable `i` should be choosen to be `i = 0， 1, ..., K-1`, other than i starting from index 1 up to K

**Comment by DmitryUlyanov** [comment]
Hello, If you look in the model you will see it has Pooling layers. Basically the input is first kind of copied K times and then pooled with different factor. There's no typo (in this part at least).
