### ISSUE TITLE
Train results. Model.state ?

### ISSUE THREAD

**Issue by nandexsp** [DmitryUlyanov/texture_nets#26]
Hi, for what is model.state? thanks

**Comment by DmitryUlyanov** [comment]
?

**Comment by 6o6o** [comment]
@nandexsp I think you're in the wrong repo. Is it [chainer-fast-neuralstyle](https://github.com/yusuketomoto/chainer-fast-neuralstyle) you're using? Model.state contains your optimizer state, allowing you to resume your training later on. Please close this.
