### ISSUE TITLE
can test.lua support CPU mode?

### ISSUE THREAD

**Issue by xpeng** [DmitryUlyanov/texture_nets#27]
Hi, since my GPU is not much good for full image size in test method, and i want to check some .t7 models generated from other machine. i think if test can support CPU(the speed is not too slow i think anyway), it will be more helpful.

**Comment by xpeng** [comment]
@DmitryUlyanov , if the test.lua can support CPU mode like chainer does, it will be more help to people who want to play and apply these amazing pre trained models while their GPU is not much powerful.  (chainer method even lead to an open models repository that peoples can share their models, this will definitely promoting the development!)
i tried to change the code but it always error since i'm not good at CUDA or cudnn, but i'm trying to make progress.

**Comment by mikeger** [comment]
@xpeng try this script where "models/model_final.t7" is the path to CUDA model
```
require 'torch'
require 'nn'
require 'cunn'
require 'cudnn'
require 'hdf5'
require 'image'
require 'src/utils'

local net = torch.load("models/model_final.t7")
cudnn.convert(net, nn)
nn.utils.recursiveType(net, 'torch.CudaTensor')
net = net:float()
print(net)
torch.save("models/model_final_nn_ascii.t7", net, 'ascii')
```

**Comment by xpeng** [comment]
@mikeger yeah, it works! thank you very much. 
i use your code to convert model and use the test code i changed to apply(i just remove the GPU relative code such as :cuda). indeed, the apply speed is not slow on CPU. cool

**Comment by DmitryUlyanov** [comment]
Updated the code, so now it can use CPU.

**Comment by xpeng** [comment]
@DmitryUlyanov thanks for update!
