### ISSUE TITLE
Problem in GenNoise Class 

### ISSUE THREAD

**Issue by ssakhavi** [DmitryUlyanov/texture_nets#3]
Hi

I've run the command:

`th stylization_process.lua -model supplementary/stylization_models/starry_style.t7 -input_image data/readme_pics/kitty.jpg -noise_depth 3`

I get an error which corresponds with the GenNoise class `updateOuput`:

`/home/siavash/torch/install/bin/luajit: bad argument #3 to '?' (number expected, got nil)
stack traceback:
	[C]: at 0x7f10f8684f30
	[C]: in function '__newindex'
	./src/utils.lua:138: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Concat.lua:12: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Concat.lua:12: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Concat.lua:12: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Concat.lua:12: in function 'updateOutput'
	/home/siavash/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	stylization_process.lua:37: in main chunk
	[C]: in function 'dofile'
	...vash/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70
`

**Comment by ssakhavi** [comment]
The problem that I've found is that the `num_planes` value for the `GenNoise` layer in the save value is not defined.

**Comment by ssakhavi** [comment]
May I ask what is the difference between the `utils` in the `src` folder and the one in the `supplementary` folder?

I also found out that you fixed the issue in the ipython files.

**Comment by DmitryUlyanov** [comment]
Hello, the files in supplementary are separate from others. They are what we've sumbitted with paper a month ago. The pretrained models should be used in iTorch notebook in supplementary folder. Because the code there is outdated it is not compatible with the rest of the repository.
