### ISSUE TITLE
How to train data

### ISSUE THREAD

**Issue by secretNninja** [DmitryUlyanov/texture_nets#31]
I am training on MS_COCO dataset. i am running this command

th train.lua -data /train/dummy -style_image data/textures/cezanne.jpg

but i am getting error
`/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:383: module 'display' not found:No LuaRocks module found for display
        no field package.preload['display']
        no file '/home/bfomitchev/.luarocks/share/lua/5.1/display.lua'
        no file '/home/bfomitchev/.luarocks/share/lua/5.1/display/init.lua'
        no file '/usr/local/share/lua/5.1/display.lua'
        no file '/usr/local/share/lua/5.1/display/init.lua'
        no file './display.lua'
        no file '/usr/local/share/luajit-2.1.0-beta1/display.lua'
        no file '/home/guest6/.luarocks/share/lua/5.1/display.lua'
        no file '/home/guest6/.luarocks/share/lua/5.1/display/init.lua'
        no file '/home/bfomitchev/.luarocks/lib/lua/5.1/display.so'
        no file '/usr/local/lib/lua/5.1/display.so'
        no file './display.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/guest6/.luarocks/lib/lua/5.1/display.so'
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/trepl/init.lua:383: in function 'require'
        train.lua:10: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
`

Thanks

**Comment by xpeng** [comment]
you need install lua module "display", use luarocks install display
