### ISSUE TITLE
getting error while training

### ISSUE THREAD

**Issue by secretNninja** [DmitryUlyanov/texture_nets#32]
while training the data this error is coming.

`threads/threads.lua:183: [thread 1 callback] bad argument #2 to '?' (dimension 1 out of range of 0D tensor at /home/xyz/torch/pkg/torch/generic/Tensor.c:19)
stack traceback:
        [C]: at 0x7ff3c8ad2830
        [C]: in function 'xpcall'
        .../xyz/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        ...t6/xyz/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...t6/xyz/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        ...t6/xyz/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
        [C]: in function 'error'
        .../xyz/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
        .../xyz/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
        .../xyz/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
        .../xyz/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
        ./dataloader.lua:52: in function '__init'
        ...xyza/torch/install/share/lua/5.1/torch/init.lua:91: in function <...xyz/torch/install/share/lua/5.1/torch/init.lua:87>
        [C]: in function 'DataLoader'
        ./dataloader.lua:28: in function 'create'
        train.lua:79: in main chunk
        [C]: in function 'dofile'
        ...xyz/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
`

**Comment by DmitryUlyanov** [comment]
make sure your dataset is correctly set up.
