### ISSUE TITLE
image.load() error

### ISSUE THREAD

**Issue by alexblickenstaff** [DmitryUlyanov/texture_nets#34]
I'm getting the below error when I try to run `test.lua` on any image that wasn't included in the repository. Even if I download an image from the repository (i.e. `https://raw.githubusercontent.com/DmitryUlyanov/texture_nets/master/data/readme_pics/karya.jpg`) I get the same error. Has anyone else run into this?

```
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/image/init.lua:220: Not a JPEG file: starts with 0x2d 0x2d
stack traceback:
	[C]: in function 'load'
	/root/torch/install/share/lua/5.1/image/init.lua:220: in function 'loader'
	/root/torch/install/share/lua/5.1/image/init.lua:368: in function 'load'
	test.lua:23: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

Similarly, for PNGs I get

```
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/image/init.lua:156: [read_png_file] File data/readme_pics/house.png is not recognized as a PNG file
stack traceback:
	[C]: in function 'load'
	/root/torch/install/share/lua/5.1/image/init.lua:156: in function 'loader'
	/root/torch/install/share/lua/5.1/image/init.lua:368: in function 'load'
	test.lua:23: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

**Comment by DmitryUlyanov** [comment]
Please, read a readme for information on how to create an image database suitable for learning.

**Comment by alexblickenstaff** [comment]
I can't find anything in the readme about image preparation; are you referring to a readme somewhere else?

**Comment by DmitryUlyanov** [comment]
https://github.com/DmitryUlyanov/texture_nets#training

**Comment by alexblickenstaff** [comment]
Is this an issue with the training setup? I thought the issue was with the image I am providing to the test.lua script. test.lua works (with the model I trained) when using images provided in the data/readme_pics folder, but does not work when using other images.

**Comment by DmitryUlyanov** [comment]
You said 

> I'm getting the below error when I try to run train.lua on any image that wasn't included in the repository

> I thought the issue was with the image I am providing to the test.lua script. test.lua works (with the model I trained) 

I am confused. Did you train a model already?

**Comment by alexblickenstaff** [comment]
Ah I'm sorry, my original comment was wrong. It is now updated. train.lua was fine, the issue was with test.lua.

**Comment by alexblickenstaff** [comment]
It looks like it's throwing the error on line 23 of `test.lua` where it fails on `image.load(params.input_image, 3)`

**Comment by alexblickenstaff** [comment]
This appears to be an issue with the `image` library; it is unrelated to your code. I will look for a solution elsewhere. Thanks!

**Comment by zhiheLu** [comment]
Have you solved the problem and can you give a good solution for me? Thanks very much.
