### ISSUE TITLE
Problem in model/pyramid.lua

### ISSUE THREAD

**Issue by fate-extra** [DmitryUlyanov/texture_nets#4]
Original code:
```lua
        -- Batch norm before merging   -- line 40
        seq:add(bn(conv_num))          -- line 41
        cur_temp:add(bn(conv_num))     -- line 42
```

Maybe the code below could be better:
```lua
        -- Batch norm before merging       -- line 40
        seq:add(bn(conv_num))              -- line 41
        cur_temp:add(bn(conv_num*(i-1)))   -- line 42
```

![texture_nets_bug](https://cloud.githubusercontent.com/assets/7439398/14075265/1705b9d4-f50a-11e5-85cf-61a0e8005e9d.png)

**Comment by fate-extra** [comment]
With this change, nn.SpatialBatchNormalization won't throw a error in CPU mode.

**Comment by DmitryUlyanov** [comment]
Wow, thanks a lot, what a disgrace...
