### ISSUE TITLE
Will it be faster to train a model on GPU rather than a CPU? how can I make it support OpenCL?

### ISSUE THREAD

**Issue by 0000sir** [DmitryUlyanov/texture_nets#55]
I'm trying to train some model, it takes many many hours to generate one. Actually I haven't got any of it after running scripts a whole day. Is it better to train it on a GPU?

I have  a AMD R2 920, but no NVIDIA, how to make this script runs on my AMD GPU?

Thank you.

**Comment by DmitryUlyanov** [comment]
Yes, it's better to use GPU. Only NVIDIA GPU's supported, for now, but as a hack  try to change this line 

https://github.com/DmitryUlyanov/texture_nets/blob/master/train.lua#L66

to `dtype = 'torch.ClTensor'`, replace all `require 'cutorch'`  with `require 'cltorch'` and remove all `cudnn` related stuff. I do not have AMD GPU so I cannot test it and push a commit myself.

**Comment by 0000sir** [comment]
Thank you but never mind, I bought a nvidia GTX1080 yestoday, it's working good, trying to get good results.
I will try it if place the AMD GPU back.
