### ISSUE TITLE
The main repo is targeting Texture but not Style transfer?

### ISSUE THREAD

**Issue by 0000sir** [DmitryUlyanov/texture_nets#56]
I tried many times, but every thing is not like what supposed to be. Until I noticed the output message "Setting up texture layer "
With neural style, the output is "Setting up style layer"
Check the codes, it's texture in it, but the param -mode is style
It seems that whatever you set -mode, it works with texture!
That's a huge mistake

**Comment by DmitryUlyanov** [comment]
Texture is a synonym for style. More, style transfer becomes texture synthesis when content weight is zero.
