### ISSUE TITLE
CPU mode

### ISSUE THREAD

**Issue by rcorin** [DmitryUlyanov/texture_nets#6]
hello! any chance you can help me trying to make it work on CPU only mode? I read about the Batchnormalization error due to your mistake, can you give details?
thanks!

**Comment by DmitryUlyanov** [comment]
Hello, trained models with the current code will work correctly on CPU, the provided pretrained models unfortunately do not work on CPU due to my mistake.

**Comment by rcorin** [comment]
Great, thanks! I tried generating one model in an amazon instance (gpu with 4gb) but it went out of memory. It'd great if you maybe can post a pretrained model with the new code so that I can try the generation part on CPU.

**Comment by DmitryUlyanov** [comment]
You can find one [here](https://github.com/szagoruyko/torch-opencv-demos/tree/master/texture_nets)
