### ISSUE TITLE
question about the preprocess 

### ISSUE THREAD

**Issue by austingg** [DmitryUlyanov/texture_nets#64]
hi, 
I am confused by the preprocess.
In the training phase, the net is fed with image substracted mean values, however, in the test phase, the net is fed with raw image and do extra deprocess. 

any help will be appreciated.

**Comment by DmitryUlyanov** [comment]
Hello, there is no preprocess stage as you described. There is one in `neural-style` repo as this preprocessing is required by VGG.

**Comment by austingg** [comment]
@DmitryUlyanov  thanks a lot. It's my careless. preprocessed image is only fed to VGG. texture nets process the raw image.
