### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by DavieHR** [DmitryUlyanov/texture_nets#7]
Hi. out of memory at /home/whr/torch-cl/extra/cutorch/lib/THC/generic/THCStorage.cu:40  when i run the  "th texture_train.lua -texture data/textures/red-peppers256.o.jpg -model_name pyramid -backend cudnn -num_iterations 1500 -vgg_no_pad true -normalize_gradients true". My GPU is Nvidia Black Titan X. What's wrong? Thx.

**Comment by DmitryUlyanov** [comment]
Hello, this is probably because if cudnn autotune, it need some memory to test methods, did you try nn backend? Does it also crash?

**Comment by DavieHR** [comment]
Yes i also tried nn backend,however, it still crashed

**Comment by DmitryUlyanov** [comment]
Got the same error, no idea, probably the implementation of something has been changed, `-batch_size 15` works for me.
