### ISSUE TITLE
where is the supplementary material mentioned in your new paper Improved Texture Networks？

### ISSUE THREAD

**Issue by JacobLee121** [DmitryUlyanov/texture_nets#78]
Improved Texture Networks mentioned in page 7 that more details can be found in the supplementary material. However I can not find the material, could you please  offer it to me?

**Comment by DmitryUlyanov** [comment]
Hi,  

Supplementary, poster, slides are in here: https://dmitryulyanov.github.io/about/

**Comment by wzm2256** [comment]
Hi, The Links are not accessible now, could you update the links?
