### ISSUE TITLE
ImageSize

### ISSUE THREAD

**Issue by DavieHR** [DmitryUlyanov/texture_nets#9]
Hi, I found that your stylization_process couldn't adaptive to different resolution,just using the resolution 800*800,etc. I fixed it.

**Comment by DmitryUlyanov** [comment]
Where did you fix it?

By the way, it is adaptive, but both width and height should be a multiple of 32.

**Comment by ycjing** [comment]
@DavieHR I have the same question. How did you fix it?  thanks
