### ISSUE TITLE
Support for CUDNN 7 please?

### ISSUE THREAD

**Issue by shubhvachher** [DmitryUlyanov/texture_nets#92]
I'm new to torch and have a fresh install just to test out fast style transfer.

After using fix in #91 changed as : `export CUDNN_PATH="/usr/lib/x86_64-linux-gnu/libcudnn.so.7"
` the error is : 

```
$ th train.lua -data ./datasets/ -style_image ./data/textures/862.png -style_size 600 -image_size 512 -model johnson -batch_size 4 -learning_rate 1e-2 -style_weight 10 -style_layers relu1_2,relu2_2,relu3_2,relu4_2 -content_layers relu4_2
Found Environment variable CUDNN_PATH = /usr/lib/x86_64-linux-gnu/libcudnn.so.7/home/user/torch/install/bin/luajit: ...e/user/torch/install/share/lua/5.1/trepl/init.lua:389: ...e/user/torch/install/share/lua/5.1/trepl/init.lua:389: /home/user/torch/install/share/lua/5.1/cudnn/ffi.lua:1618: 
These bindings are for CUDNN 5.x (5005 <= cudnn.version > 6000) , while the loaded CuDNN is version: 7101  
Are you using an older or newer version of CuDNN?
stack traceback:
	[C]: in function 'error'
	...e/user/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train.lua:5: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

Is there a quick fix way to add support for CUDNN 7? If so, how can I get it done. I would really like to test this code.

I realize, being new to this, I may be missing something fundamental because every one of tensorflow, cuda, cudnn, torch, etc. have a combination of version numbers that is tested and only that combination works without hacks. Is the process to hack in CUDNN 7 complicated?

**Comment by DmitryUlyanov** [comment]
Hi, Unfortunately I cannot help you with this issue. This code uses
torch7 as a framework, which probably does not support cudnn 7. Or you
did not install it in the right way. Please, try to ask at torch7
issues or forums.

**Comment by shubhvachher** [comment]
Followed the instructions here for the install : http://torch.ch/docs/getting-started.html

**Comment by shubhvachher** [comment]
Alright! Solution here https://github.com/torch/torch7/issues/1133#issuecomment-376038963

Thanks for the quick reply @DmitryUlyanov
